const reviews = [
  {
    title: "Student Information Management System",
    des1: "The Student Information Management System is a module to simplify the data management process for each organization.",
    des2: "Our institute ERP saves time and resources by offering online student registration link. This allows students to fill out their own registration form which avoids spelling mistakes. It has OTP validation to get the exact contact number of the students.",
    des3: "With full administrative access, the higher management can manage the students information effectively, can track and get centralized report of students from enrollment to certification.",
    des4: "Student information management system helps to enhance productivity, no need to maintain files, avoid manual work.",
    url: "https://zenoxerp.com/assets-web/img/demo-content/icons/20-email-marketing-details.svg",
  },
  {
    title: "Admission Management System",
    des1: "ZenoxERP is the best school management system that manage the student enrollment process effortlessly.",
    des2: "An admission management system automates entire admission process of institutions with its unique features.",
    des3: "Admission management system eliminates paperwork, reduces workload & streamlines the enrollment process.",
    des4: "ZenoxERP School management system has adopted advanced technology to improve admission ratio & institute performance.",
    url: "https://zenoxerp.com/assets-web/img/demo-content/icons/21-ppc-details.svg",
  },
  {
    title: "Fee Management System",
    des1: "Our school ERP has a world class fee management system that offers safe, secure, accurate & quick fees collection system.",
    des2: "ZenoxERP school management system sends automated fees reminder before its due, it helps to collect on time fees.",
    des3: "It supports online payment gateway integration which allows students/parents to make fee payments at their convenience.",
    des4: "Our school management system generates a variety of fee receipts and helps to send them with an attachment.",
    url: "https://zenoxerp.com/assets-web/img/demo-content/icons/07-we-offer.svg",
  },
  {
    title: "Attendance Management System",
    des1: "ZenoxERP attendance management system allows users to integrate QR code based & biometrics system.",
    des2: "Our attendance management system helps institute to track records of student and employee in/out timing.",
    des3: "It will send automatic messages & notification to parents, admin on successful attendance of students.",
    des4: "Make your mobile a QR code scanner to mark daily batch wise attendance in ZenoxERP Attendance management system.",
    url: "https://zenoxerp.com/assets-web/img/demo-content/icons/17-local-details.svg",
  },
  {
    title: "e-Learning (LMS)",
    des1: "LMS is used to help streamline the delivery of online learning for educational institutions, allowing for a more connected and accessible educational experience for students.",
    des2: "Customized LMS for all the learning needs of your organization. ZenoxERP is a leading LMS provider for various educational institutes.",
    des3: "Our secure and reliable learning platform is customized to meet the functional requirements of Educational Institutions.",
    des4: "Our Learning management system enables collaborative & engaging online learning experiences.",
    url: "https://zenoxerp.com/assets-web/img/demo-content/icons/20-email-marketing-details.svg",
  },
  {
    title: "White Label Mobile App",
    des1: "ZenoxERP provides a white-label mobile app for schools & educational institutes.",
    des2: "A customizable app is perfect for groups running multiple Educational Institutes & Schools.",
    des3: "The White Label mobile app offers an effective way to stand out among your competitors.",
    des4: "ZenoxERP can be personalized and designed to match individual schools, educational institutes including branding, icons, colors & much more",
    url: "https://zenoxerp.com/assets-web/img/demo-content/icons/21-ppc-details.svg",
  },
  {
    title: "Online Payment Integrations",
    des1: "Making collection of School / Education institute fees simple for the administration.",
    des2: "Integration of online payment system with the school management software is not only beneficial to the parents, but also to the school & education institute management.",
    des3: "Online payment gateway integration facilitates the parents to pay the fee online using the payment gateway from anywhere.",
    des4: "With our extensive experience with payment gateway services and implementations ZenoxERP with mobile app can easily help you out.",
    url: "https://zenoxerp.com/assets-web/img/demo-content/icons/07-we-offer.svg",
  },
  {
    title: "Online Shopping Store",
    des1: "ZenoxERP computerized online store feature gives a bird’s eye view of all your school essentials.",
    des2: "It helps to manage stocks coming in, also maintains the sales and purchases records with date and time.",
    des3: "The online store feature allows school, educational institute to manage and organize all the items available in the school premises.",
    des4: "It includes uniforms, books, stationery items, sports items and other stuff to distribute among students or teachers, and keep track of the same.",
    url: "https://zenoxerp.com/assets-web/img/demo-content/icons/17-local-details.svg",
  },
  {
    title: "Franchise Management",
    des1: "ZenoxERP is the trailblazing franchise software for learning institutions.",
    des2: "ZenoxERP franchise management has two division namely organization and branch. Learning institutions are able to expand and to add several branches.",
    des3: "With organization user, a learning institution is able to have access to all branches from a single login and in branch user a learning institution is able to open its own branches.",
    des4: "ZenoxERP software helps franchiser by providing detailed financial reports on the entire organization. You can manage like student, course, subject, time table, fees schedule, franchise expenditure etc.",
    url: "https://zenoxerp.com/assets-web/img/demo-content/icons/18-smm-details.svg",
  },
];

export default reviews;
